name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0, 8.1]
        include:
          - php: "7.4"
            analysis: true
          - php: "8.0"
            analysis: true
          - php: "8.1"
            analysis: true
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer
        run: composer install
      - name: Run Code Sniffer
        if: matrix.analysis
        run: composer cs
      - name: Run Tests
        run: composer test
